stepBuildImage/stepIntegrationTest: Sanitizers
gyroidos/gyroidos_ci_common pull request #8
Opened 2024-06-03 10:10 UTC by k0ch4lo

This PR introduces support for building and testing the CML with sanitizers enabled.

2024-07-01 11:54 UTC, jwsbck requested changes

2024-07-01 11:54 UTC, jwsbck commented on Jenkinsfile
> +				build job: "../gyroidos/PR-42", wait: true, parameters: [
? :-)

2024-07-04 05:53 UTC, k0ch4lo commented on Jenkinsfile
> +				build job: "../gyroidos/PR-42", wait: true, parameters: [
thnx, closing this one ;-)

2024-07-08 07:20 UTC, jwsbck approved these changes

2024-07-09 12:50 UTC, merged